# Welcome to Jekyll!
#

# Site settings
title: BioJava
description: |
  BioJava is an open-source project
  dedicated to providing a Java framework
  for processing biological data.
owner: BioJava
first_published: 2000
email: biojava-l@biojava.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://biojava.org" # the base hostname & protocol for your site
google_analytics: UA-1326640-1
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/biojava
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:biojava-l@biojava.org
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
sitemap: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#sass:
#  style: compressed

# Release settings
release:
 version: 5.0.0
 legacy: 1.9.1

collections:
  wiki:
   output: true
   permalink: /wiki/:path/
   post_dirs: false
   layout: page

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: page
